# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('timeout', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('url_hash', models.CharField(db_index=True, max_length=34, unique=True)),
                ('download_status', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeout', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('is_404', models.BooleanField(default=False)),
                ('is_500', models.BooleanField(default=False)),
                ('is_300', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('url_hash', models.CharField(db_index=True, max_length=34, unique=True)),
                ('content_hash', models.CharField(max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
