# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('depth', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
