# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.TextField(),
        ),
    ]
