# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180406_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_hash',
            field=models.CharField(default=1, max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='url_hash',
            field=models.CharField(default=1, max_length=34),
            preserve_default=False,
        ),
    ]
