# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180501_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlink',
            name='download_status',
            field=models.IntegerField(choices=[(0, 'open for download'), (1, 'some worker is downloading'), (2, 'downloaded and saved')], default=0),
        ),
    ]
