# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20180406_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_hash',
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
