# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20180406_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 11, 8, 17, 18, 750125, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
