# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_page_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('url_hash', models.CharField(max_length=34, unique=True)),
                ('download_status', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
