# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_outlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('timeout', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='outlink',
            name='last_attempt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outlink',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
    ]
