# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_outlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('timeout', models.DateTimeField(default=False)),
                ('last_timeout', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='outlink',
            name='last_attempt',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 11, 7, 53, 171980, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlink',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
    ]
