# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20180415_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlink',
            name='is_404',
            field=models.BooleanField(default=False),
        ),
    ]
