# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_outlink_is_404'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlink',
            name='is_300',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlink',
            name='is_500',
            field=models.BooleanField(default=False),
        ),
    ]
