# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20180416_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlink',
            name='url_hash',
            field=models.CharField(db_index=True, max_length=34, unique=True),
        ),
    ]
