# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20180418_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_hash',
            field=models.CharField(db_index=True, max_length=34, unique=True),
        ),
    ]
