# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20180418_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.IntegerField(null=True)),
            ],
        ),
    ]
