# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
